### ISSUE TITLE
Adding second snippet call produces 500 system error

### ISSUE THREAD

**Issue by JurnSpijksma** [joeke/modx-minify#1]
Fix: The minify class should be required once at line number 6 and line number 19.

**Comment by joeke** [comment]
Should be fixed now in latest release.

**Comment by ilyamio** [comment]
Hello! When adding `<script type="text/javascript" src="[[!modxMinify?&group=`frontjsfiles`]]"></script>` the site goes down and gives 500 error. 
I call snippet twice. First for css and second for js files. I tried to call just snippet for js. Anyway, site goes down with 500 error. There are no errors in log files. How can it be solved? Thanks.

**Comment by inreti-sb** [comment]
There are the backticks missing in your snippet call.

`[[!modxMinify?&group=`css`]]`
See: https://github.com/Sterc/modx-minify

Does this help?

**Comment by ilyamio** [comment]
> Hello! When adding `<script type="text/javascript" src="[[!modxMinify?&group=`frontjsfiles`]]"></script>` the site goes down and gives 500 error. I call snippet twice. First for css and second for js files. I tried to call just snippet for js. Anyway, site goes down with 500 error. There are no errors in log files. How can it be solved? Thanks.

This issue is solved! Problem was in one js file. I separated it from the snippet and the 500 error disappeared.
